
import { Nunito } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'


import AppInitializer from "@/components/general-components/Initializer";

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

	return (
		<html lang='ru'>
			<body className={`${nunito.className} antialiased dark`}>
				<Providers>
					<AppInitializer />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
