import { Nunito } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './providers'
import { Toaster } from '@/components/ui/sonner'

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='ru'>
			<body className={`${nunito.className} antialiased dark`}>
				<main className='max-w-6xl mx-auto'>
					<AuthProvider>{children}</AuthProvider>
				</main>
				<Toaster />
			</body>
		</html>
	)
}
